version: '3'
services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq-local
    ports:
      - "4369:4369"
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - messaging

networks: 
    messaging:
      driver: bridge
